language: node_js
node_js:
- 6.9.2
deploy:
  - provider: npm
    email: david.beale@bealearts.co.uk
    api_key:
      secure: "bw5UNHe9T92kG+B2wcKfZpDIcjyaGBjRD3o+1+Fs8N8ZcUVEfPLYeisPUXkfOtxXq2pyk11whez10lTUaLoIe9J3dUu/v+XHyBac9f/B5hAvgnQT94oQHRmv/JPDlCarRCJr9UTbMzVA/elnp/jdMIY+025ZnSt46LNCMNpv9mm+pkL0W9nYn2ShoVwWzCEqL64G/3tuOl9TPncItO0Uk+WVt2REKhoRnESNJeVCvHt+xPNybrksebuQ4BFEYrDdlPQYianl1N2FyT5iFFnsqDDHkoB5n/RcPC0x9if77dgthYP+63R2wg5gc7dhTNuT55qoBtybw+7vwj9DMR255sclUVgi+l0mCKsx+3LRzhDuTBOVL+5n60e5+IYH8QTrgIYuFaGeO+jx9R+AF9+LxFWFox/KlTKvTY46o40NPWTDNYdkvhGBNc0Hw/EUPoKWuRwCUeWdZKdOoLXLhzoYW6yRfCk/khu+OUYExx7s80UD+uPJczjeioTwUbg/f7mrx5akp1+8b4I/uA6ETl0f+6r9th1UVbLsoFp5aRCymTFeFlg2lpybdY450nBz+ePHvocTb+yugRfQhXh4eq1CxxPecc1vCZV857N2XJCRXYAiEu9TS1R43IKc2H0kUETL0xMi0O22IRsZ8Id3iP6lssurTOViY365/B8UFynVcq0="
    on:
      tags: true
      repo: bealearts/qlik-sense-webpack-plugin
  - provider: releases
    api_key:
      secure: oxOazztBffPekKiZUmy9sDfzzBIw+m0DW3AgiDd0SyRkqts6CSee5cJb6N4eoDlQbiPPQS6v9VNVlkiZ2HM3EEWeUuY7uNH9/WXwxi0kJli5CUeGfIAUsKOXjUPu0qW0y+fH1Lv+FfbUcUdN52v8BNWY8pLXad7ZUW9lAoHEuboRk16C7WfX31K8PzfOb9RM53Ge+FXSwUI9wmrdvszPqNS3v7a0T2DogjvrUeASvYDSSjh2biiEox84DX/YNG4sS8Z5De8czV1FQbVLTyd1m8YcKNYT/k1cCRSaOG7rQY/UZGEFrHuSf6ZQPpc+ENqIMecKO7T5KwuGSM0hRUR5McKPGeVTyn1xq6Gw13GD+ekVCjWamt8LePhFJb3+6hZEUHApd1izCJiS9l0LmDzrqe9v7X2yNR46F2UR0QIbRsn1w/XxGZrR6Tk2mlhMHaeZBwFI8sP0hbOIfAp7jlYN3m+7qvrGqLUJpr/Zo9saPpCQJ5CBvsAYex/ij1AyUKGCpU/BBHUQsoDOn8gAPp8i9b3/CNy3Iakp06/tqXshQAStIoEbo9IfkFg3vTTclkr4sLy9zqYexcbvB8rmHmB0+bTfuX8PwcVJMRWVmI5UpTRPHVfiyWR5f4M94OD1WHPk7pLDFrol85UMQutsE08bB+0e2zT1eeFwdLAkcRy8Ysw=
    on:
      tags: true
      repo: bealearts/qlik-sense-webpack-plugin
